### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LMJayasundara** [KishoreKaushal/nodeopencv#1]
Did you do that bro?

**Comment by KishoreKaushal** [comment]
I am sorry, I didn't get your question. Could you be more specific?

**Comment by Shanmax1996** [comment]
I asked bro, did you complete this project.

**Comment by Shanmax1996** [comment]
Is it working fine or not

**Comment by KishoreKaushal** [comment]
It is not working properly, because of some compiler issue which I was not able to resolve. Instead we shifted to use the opencv.js which is a better choice.

**Comment by Shanmax1996** [comment]
Ah okay.thank you
